version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  parse-server:
    image: elestio/parse-server:${SOFTWARE_VERSION_TAG}
    container_name: parse-server
    hostname: parse-server
    restart: always
    ports:
      - 1337:1337
    links:
      - mongo
    environment:
      - PARSE_SERVER_APPLICATION_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_SERVER_MASTER_KEY=${MASTER_KEY}
      - PARSE_SERVER_REST_API_KEY=${REST_KEY}
      - PARSE_SERVER_DATABASE_URI=mongodb://mongo:27017/${APP_NAME}
      - PARSE_SERVER_START_LIVE_QUERY_SERVER=1
      # - PARSE_SERVER_LIVE_QUERY={"classNames":["people","monitor"]}
      - PARSE_SERVER_MASTER_KEY_IPS=0.0.0.0/0
      # - PARSE_SERVER_ALLOW_CLIENT_CLASS_CREATION=allowClientClassCreation

  dashboard:
    image: elestio/parse-dashboard:${SOFTWARE_VERSION_TAG}
    container_name: dashboard
    restart: always
    ports:
      - "4040:4040"
    links:
      - parse-server
    environment:
      - PARSE_DASHBOARD_SERVER_URL=${BASE_URL}:1337/parse
      - PARSE_DASHBOARD_APP_NAME=${APP_NAME}
      - PARSE_DASHBOARD_APP_ID=${PARSE_SERVER_APPLICATION_ID}
      - PARSE_DASHBOARD_MASTER_KEY=${MASTER_KEY}
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
      - PARSE_DASHBOARD_USER_ID=${ADMIN_USERNAME}
      - PARSE_DASHBOARD_USER_PASSWORD=${ADMIN_PASSWORD}
